<a href="https://colab.research.google.com/github/paratesai316/FDS-Google-Colabs/blob/main/FDS_test_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Question 1
#A weather station records temperatures in C as

import numpy as np
data = [22.5 , 23.1 , 24.8 , 21.2 , 19.9]
array = np.array(data)
print("1. \nShape of array:\t", np.shape(array),"\n")
print("2. \nMean temperature:\t", np.mean(array),"\n")
sorted_array = np.sort(array)
print("3. \nSorted array:\t", sorted_array,"\n")

1. 
Shape of array:	 (5,) 

2. 
Mean temperature:	 22.3 

3. 
Sorted array:	 [19.9 21.2 22.5 23.1 24.8] 



In [ ]:
#Question 2
#You have two quarterly sales arrays

import numpy as np
Q1 = np.array([500 , 600 , 700])
Q2 = np.array([450 , 550 , 800])

concarray = np.vstack((Q1, Q2))
print("1. \nConcatenated array:\n",concarray,"\n")
splitarray = np.split(concarray,1)
print("2. \nSplit array:\n",splitarray,"\n")

1. 
Concatenated array:
 [[500 600 700]
 [450 550 800]] 

2. 
Split array:
 [array([[500, 600, 700],
       [450, 550, 800]])] 



In [ ]:
#Question 3
#Given a NumPy array of stock prices:

import numpy as np
prices = np.array([120 , 122 , 121 , 125 , 123 , 124])
reshapedarray = np.reshape(prices, (3,2))
horz_split = np.hsplit(reshapedarray,2)
deep_copy = horz_split[0]
print(deep_copy)

[[120]
 [121]
 [123]]


In [ ]:
#Question 4
#Given a 2D dataset:

import numpy as np
X = np.array([[1 , 2] , [3 , 4] , [5 , 6]])
cov_X = np.cov(X.T)
print("1. \nCovariance Matric",cov_X,"\n")
eig_val,eig_vec = np.linalg.eig(cov_X)
print("2. \nEigenvalues",eig_val,"\n")
print("3. \nEigenvectors",eig_vec,"\n")

1. 
Covariance Matric [[4. 4.]
 [4. 4.]] 

2. 
Eigenvalues [8. 0.] 

3. 
Eigenvectors [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 



In [ ]:
#Question 5
#Simulate 1000 trials of stock returns assuming:

normal_returns = np.random.normal(loc=0.05, scale=0.1, size=1000)

print("Simulation of Stock Returns\n")
print(normal_returns,"\n\n")

posson_returns = np.random.poisson(lam=3, size=1000)

print("Simulation with Posson Distribution\n")
print(posson_returns)

Simulation of Stock Returns

[-7.97157773e-02  3.89585113e-02  7.47190743e-02  3.67816575e-02
  1.00967478e-02  4.69141335e-02  8.77362334e-02  6.38780268e-03
  1.24475263e-01 -1.95809112e-01  6.54247460e-02 -3.61411566e-02
  1.12797689e-01  6.14156327e-03  3.48693432e-02 -5.63907951e-02
  3.10615996e-01 -5.29614566e-02  1.22542088e-01 -1.92732774e-01
 -1.23314925e-02  1.86830921e-01 -9.10386778e-02  8.96795410e-02
  1.63591694e-01  1.15392841e-01  1.54353658e-01 -1.46569824e-01
  1.22730974e-02  2.56120252e-01  2.42175482e-01  1.16917082e-01
  4.43849563e-02 -6.57569467e-02  2.01111501e-02  6.46543229e-02
  6.58863765e-02  5.35276971e-02  4.80015888e-02  7.42563316e-02
 -2.31135295e-01  2.29773505e-02  2.33927297e-01  1.54913873e-01
 -6.40186422e-02 -4.29957567e-02  5.52323499e-02 -1.59181633e-02
  5.55445820e-02 -1.86134202e-02  4.37864537e-02 -8.31970274e-04
  2.39847799e-01  4.42526045e-02  2.13251701e-01  1.10310247e-02
  1.60885496e-02  1.48547076e-01 -1.29545358e-01  1.12614285e