<a href="https://colab.research.google.com/github/paratesai316/FDS-Goole-Colabs/blob/main/RA2411056010288_unit1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

```
Sai Parate
RA2411056010288
```



In [ ]:
import numpy as np

array1 = np.arange(0,24,6).reshape(2,2)
print(array1)
copy1 = np.empty_like(array1)
print(copy1)
copy2 = array1
print(copy2)
copy3 = np.copy(array1)
print(copy2)

[[ 0  6]
 [12 18]]
[[         1025821751                   0]
 [                427 2268721830212730880]]
[[ 0  6]
 [12 18]]
[[ 0  6]
 [12 18]]


In [ ]:
import numpy as np

array = np.arange(0,6)
print(array)
copy = np.copy(array)
copy[3] = 6
print(copy)

[0 1 2 3 4 5]
[0 1 2 6 4 5]


In [ ]:
import numpy as np

array = np.arange(0,18,1).reshape(2,3,3)
print(array,"\n\n")
for x in array:
  for y in x:
    for z in y:
      print(f"{z}\t",end="")
    print("\n\t")
  print("\n\t")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]] 


0	1	2	
	
3	4	5	
	
6	7	8	
	

	
9	10	11	
	
12	13	14	
	
15	16	17	
	

	


In [ ]:
import numpy as np

array1 = np.array([[10,20],[30,40],[50,60]])

print(array1,"\n")
print("1. ",type(array1),"\n")
print("2. ",array1.shape,"\n")
print("3. ",array1.ndim,"\n")
print("4. ",array1.size,"\n")
print("5. ",array1.dtype,"\n")
print("6. \n",np.ndarray(shape=(3,3),dtype=float),"\n")

array2 = np.ones((3,3))
print("7. \n",(array2),"\n")

array3 = np.zeros((3,3))
print("8. \n",(array3),"\n")

array4 = np.full((3,3),4,dtype=complex)
print("9. \n",(array4),"\n")
#array1[[2],[1]] = 20
print("10. \n",array1[2][1],"\n")

array5 = [[1,2],[3,4],[5,6]]
print("11. \n",array1+array5,"\n")
print("12. \n",array1-array5,"\n")
print("13. \n",array1*array5,"\n")
print("14. \n",array1/array5,"\n")

print("15. \n",array1.itemsize)

[[10 20]
 [30 40]
 [50 60]] 

1.  <class 'numpy.ndarray'> 

2.  (3, 2) 

3.  2 

4.  6 

5.  int64 

6. 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

7. 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

8. 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

9. 
 [[4.+0.j 4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j 4.+0.j]
 [4.+0.j 4.+0.j 4.+0.j]] 

10. 
 60 

11. 
 [[11 22]
 [33 44]
 [55 66]] 

12. 
 [[ 9 18]
 [27 36]
 [45 54]] 

13. 
 [[ 10  40]
 [ 90 160]
 [250 360]] 

14. 
 [[10. 10.]
 [10. 10.]
 [10. 10.]] 

15. 
 8


In [ ]:
import numpy as np
array1 = [[2,-1,0,15,5],[1,1,1,1,0]]
array2 = [[10,20,5,7,8],[10,2,-1,4,5]]
print("1. \n", array1,"\n")
print("2. \n", array2,"\n")

print("3. \n", np.concatenate((array1,array2)),"\n")
print("4. \n", np.concatenate((array1,array2),axis=0),"\n")
print("5. \n", np.concatenate((array1,array2),axis=1),"\n")

print("6. \n", np.stack((array1,array2),axis=0),"\n")
print("7. \n", np.stack((array1,array2),axis=1),"\n")

print("8. \n", np.hstack((array1,array2)))
print("9. \n", np.vstack((array1,array2)))



1. 
 [[2, -1, 0, 15, 5], [1, 1, 1, 1, 0]] 

2. 
 [[10, 20, 5, 7, 8], [10, 2, -1, 4, 5]] 

3. 
 [[ 2 -1  0 15  5]
 [ 1  1  1  1  0]
 [10 20  5  7  8]
 [10  2 -1  4  5]] 

4. 
 [[ 2 -1  0 15  5]
 [ 1  1  1  1  0]
 [10 20  5  7  8]
 [10  2 -1  4  5]] 

5. 
 [[ 2 -1  0 15  5 10 20  5  7  8]
 [ 1  1  1  1  0 10  2 -1  4  5]] 

6. 
 [[[ 2 -1  0 15  5]
  [ 1  1  1  1  0]]

 [[10 20  5  7  8]
  [10  2 -1  4  5]]] 

7. 
 [[[ 2 -1  0 15  5]
  [10 20  5  7  8]]

 [[ 1  1  1  1  0]
  [10  2 -1  4  5]]] 

8. 
 [[ 2 -1  0 15  5 10 20  5  7  8]
 [ 1  1  1  1  0 10  2 -1  4  5]]
9. 
 [[ 2 -1  0 15  5]
 [ 1  1  1  1  0]
 [10 20  5  7  8]
 [10  2 -1  4  5]]


In [ ]:
import numpy as np
array1 = np.array([2,-1,0,15,5,1,1,1,1,0])
print("1. \n", np.split(array1,2))
print("2. \n", np.array_split(array1,3))

1. 
 [array([ 2, -1,  0, 15,  5]), array([1, 1, 1, 1, 0])]
2. 
 [array([ 2, -1,  0, 15]), array([5, 1, 1]), array([1, 1, 0])]
